/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hardwarestore;


import java.io.File;
import java.io.FileNotFoundException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author thisa
 */
public class ViewTransactionlogs extends javax.swing.JFrame {

    /**
     * Creates new form TransactionLogs
     */
    private Connection con = null;
    private PreparedStatement pst;
    private ResultSet rs; 
    private String logDate;

    public ViewTransactionlogs() {
        initComponents();
       
    }

     public ViewTransactionlogs(String logDate) {
        initComponents();
        HelperClass.Date(jLabel2);
        HelperClass.ShowTime(jLabel4);
        con = HelperClass.connect();
        this.logDate = logDate;
        getTransInformation();

    }
    

    /**
     * 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
     
    public void getTransInformation (){
      //Read file and assign data.
       try{
                File file = new File("C:\\Users\\THR\\Documents\\NetBeansProjects\\HardwareSaves\\DailyTransactions\\" + logDate + ".txt"); //TransLog
                Scanner scan;
                System.out.println(logDate );  
                /*
                String starr[] = new String[100];

                starr[0] = "buttercups";
                starr[1] = "strawberry";

                System.out.println(starr[0] + "\n");  
                System.out.println(starr[1] + "\n");
                */
                
                
                
                try {
                    scan = new Scanner(file);
                    String sd[] = new String[100] ;   
                    int i = 0;
                    int c = 0;
                    while (scan.hasNextLine()){
                        
                        sd[i] = scan.nextLine();
                        i++;
                        c = i;
                    }
                    
                    System.out.println(c); 
                    
                    for (int k = 3; k < c; k++){
                        System.out.println(sd[k]);  
                     
                        if(sd[k].equals("------GOODS TRANSACTIONS------")){
                            k = k+3;
                           
                            while(sd[k].equals("") == false){
                                System.out.println(sd[k]+ "__") ;  
                                k++;
                            }
                        }
                        if(sd[k].equals("------OTHER TRANSACTIONS------")){
                            k = k+3;
                           
                            while(sd[k].equals("") == false){
                                System.out.println(sd[k]+ "__") ;  
                                k++;
                            }
                        }
                        if(sd[k].equals("-----SUMMARY----")){
                            k = k+3;
                           
                            while(k != c){
                                System.out.println(sd[k]+ "__") ;  
                                k++;
                            }
                        }
                    
                    }
                    //

                } catch (FileNotFoundException ex) {
                    Logger.getLogger(ViewTransactionlogs.class.getName()).log(Level.SEVERE, null, ex);
                }
 
        }catch(Exception e){
           JOptionPane.showMessageDialog(this, "No log found similar to this date! ");
        }
            
    }
     
     
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        DailyGoodsTransactionTable = new javax.swing.JTable();
        TransactionNoLabel4 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        TransactionNoLabel5 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        TransactionNoLabel6 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        TransactionNoLabel7 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        TransactionNoLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        otherTranscationsjTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel2.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N
        jLabel2.setText("DD/MM/YY");

        jLabel1.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        jLabel1.setText("Date:");

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        jLabel5.setText("View Transaction Log");

        jLabel3.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        jLabel3.setText("Time:");

        jLabel4.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N
        jLabel4.setText("Min/Sec");

        DailyGoodsTransactionTable.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        DailyGoodsTransactionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Incompletence", "Trans No", "Date", "Time", "Item No", "Description", "Quantity", "Sold Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        DailyGoodsTransactionTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DailyGoodsTransactionTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(DailyGoodsTransactionTable);

        TransactionNoLabel4.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        TransactionNoLabel4.setText("-------------Summary--------------");

        jButton9.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jButton9.setText("Back");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N
        jLabel17.setText("No of Items Sold:");

        TransactionNoLabel5.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N
        TransactionNoLabel5.setText("No of Items");

        jLabel18.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N
        jLabel18.setText("Other Transaction Left Amount:");

        TransactionNoLabel6.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N
        TransactionNoLabel6.setText("OtherT");

        jLabel19.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N
        jLabel19.setText("Total Goods Amount:");

        TransactionNoLabel7.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N
        TransactionNoLabel7.setText("goodsAmt");

        jLabel20.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N
        jLabel20.setText("Goods Sales Profit:");

        TransactionNoLabel8.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N
        TransactionNoLabel8.setText("Goods Profit");

        otherTranscationsjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Trans_ID", "Date", "Time", "Description", "In or Out", "Amount(Rs.)"
            }
        ));
        otherTranscationsjTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                otherTranscationsjTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(otherTranscationsjTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(TransactionNoLabel7)
                                .addComponent(jLabel19))
                            .addComponent(jLabel18)
                            .addComponent(TransactionNoLabel4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel17))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TransactionNoLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TransactionNoLabel5)
                                    .addComponent(TransactionNoLabel8)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addGap(64, 64, 64))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 920, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 920, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 49, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(TransactionNoLabel4)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel19)
                        .addGap(18, 18, 18)
                        .addComponent(TransactionNoLabel7)
                        .addGap(52, 52, 52)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TransactionNoLabel6)
                        .addGap(92, 92, 92)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(TransactionNoLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(TransactionNoLabel8)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        this.dispose();
        TransactionLogs ob = new TransactionLogs();  //**i have changed the parameterized constructor
        ob.setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void DailyGoodsTransactionTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DailyGoodsTransactionTableMouseClicked

    }//GEN-LAST:event_DailyGoodsTransactionTableMouseClicked

    private void otherTranscationsjTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_otherTranscationsjTableMouseClicked

      
    }//GEN-LAST:event_otherTranscationsjTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewTransactionlogs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewTransactionlogs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewTransactionlogs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewTransactionlogs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewTransactionlogs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable DailyGoodsTransactionTable;
    private javax.swing.JLabel TransactionNoLabel4;
    private javax.swing.JLabel TransactionNoLabel5;
    private javax.swing.JLabel TransactionNoLabel6;
    private javax.swing.JLabel TransactionNoLabel7;
    private javax.swing.JLabel TransactionNoLabel8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable otherTranscationsjTable;
    // End of variables declaration//GEN-END:variables
}
